# Generated by Django 5.2.1 on 2025-05-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('weather', models.CharField(max_length=1024)),
                ('scan_time', models.DateTimeField()),
                ('fact', models.CharField(max_length=1024, null=True)),
                ('cnt', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
    ]
